app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired


class NameForm(FlaskForm):
    name = StringField('Enter Your name', validators=[DataRequired()])
    password = PasswordField('Provide Your password', validators=[DataRequired()])
    submit = SubmitField('Submit')

class SignUpForm(FlaskForm):
    name = StringField('Enter Your name', validators=[DataRequired()])
    password = PasswordField('Provide Your password', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from app import *
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config
from pymongo import MongoClient
from . import main


bootstrap = Bootstrap()
db = None

def create_app(config_name):
    global db
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    app.register_blueprint(main.main_test)
    bootstrap = Bootstrap(app)
    client = MongoClient(app.config['PYMONGO_DATABASE_URI'])
    db = client[app.config['PYMONGO_DB']]

    return app

app/main/__init__.py
from flask import Blueprint

main_test = Blueprint('main', __name__)

from . import views

app/main/views.py
from app import *
from flask import redirect, url_for, session, render_template
from . import main_test
from .forms import NameForm, SignUpForm


@main_test.route('/', methods=['GET', 'POST'])
def index():
    form = NameForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        return redirect(url_for('.index'))
    return render_template('index.html', form=form, name=session.get('name'))

@main_test.route('/sign_up', methods=['GET','POST'])
def sign_up():
    form = SignUpForm()
    if form.validate_on_submit():
        db.users.insert_one({"name": form.name.data})
        return redirect(url_for('.index'))
    return render_template('sign_up.html', form = form)

@main_test.route('/test_db', methods=['GET'])
def test_db():
    coll = db['restaurants']
    restaurants = list(coll.find({"grades.score": {"$gt": 90}}))
    return render_template('db_test.html', name=session.get('name'), restaurants = restaurants)

@main_test.route('/logout')
def logout():
    session['name'] = None
    return redirect(url_for('.index'))

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Assignment1_test{% endblock %}

{% block head %}
{{ super() }}
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Flasky</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                <li><a href="{{ url_for('main.sign_up') }}">Sign Up</a></li>
                <li><a href="{{ url_for('main.logout') }}">Logout</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/db_test.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}db_test{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Hello, {% if name %}{{ name }}{% else %}Stranger!{% endif %}!</h1>
    <h4>Restaurants list:</h4>
</div>
{% for restaurant in restaurants %}
    <div class=restaurant>{{ restaurant.name }}</div>
{% endfor %}
    <a href="{{ url_for('main.index') }}">Go Back...</a>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Assignment1_test{% endblock %}

{% block page_content %}
    {% if name %}
    Welcome {{ name }}
    {% else %}
        Kindly Login
        {{ wtf.quick_form(form) }}
    {% endif %}


{% endblock %}

app/templates/sign_up.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Sign Up{% endblock %}

{% block page_content %}
    Sign Up
    {{ wtf.quick_form(form) }}
{% endblock %}